name       = "dynload-julia"
description= "Dynamically load Julia from Fortran"
version    = "0.1.0"
license    = "MIT"
author     = "Carlos Une"
copyright  = "2021 Carlos Une"
maintainer = "Carlos Une <@brocolis>"
homepage   = "https://github.com/brocolis/dynload-julia"
categories = ["dynamic loader"]
keywords   = ["julia"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true

# Some linux distros don't work with `--flag -ldl`
# If that is the case, uncomment the following line
# link = "dl"

[dependencies]
dynload-base = { git = "https://github.com/brocolis/dynload-base.git" }
c-util = { git = "https://github.com/brocolis/c-util.git" }

[install]
library = false
