name: fpm

on: [push, pull_request]

jobs:
  gfortran:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        gcc_v: [9] # Version of GFortran we want to use.
        include:
        - os: ubuntu-latest
          os-arch: linux-x86_64

        - os: windows-latest
          os-arch: windows-x86_64

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
          version: '1.6'

    - name: Run tests (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        gfortran --version
        julia --version
        sed -i "s/^# link/link/" fpm.toml
        export LD_LIBRARY_PATH=$(dirname $(which julia))/../lib
        fpm test

    - name: Run tests
      run: |
        gfortran --version
        julia --version
        fpm test
